version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: amrs_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  tests:
    build:
      context: .
      target: test
    container_name: fastapi_tests
    depends_on:
      - db
    networks:
      - app_network
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

  app:
    build:
      context: .
      target: production
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - tests
    networks:
      - app_network
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge